# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset BINMOSQUITTO_PUB_PHONY
	unset BINMOSQUITTO_PUB_PHONY_CLEAN
	if [ "${HAVE_BIN_MOSQUITTO_PUB}" = "1" ]; then
		export BINMOSQUITTO_PUB_NAME="mosquitto_pub"
		export BINMOSQUITTO_PUB="$1"
		export BINMOSQUITTO_PUB_OBJS_DIR=${RUNTIME_OBJS}${BINMOSQUITTO_PUB/${ROOT}/""}
		export BINMOSQUITTO_PUB_BIN="${RUNTIME_BIN}/${BINMOSQUITTO_PUB_NAME}${BINSUFFIX}"
		export BINMOSQUITTO_PUB_BIN_CLEAN="${BINMOSQUITTO_PUB_BIN}_clean"
		export BINMOSQUITTO_PUB_PHONY="BINMOSQUITTO_PUB"
		export BINMOSQUITTO_PUB_PHONY_DEV="BINMOSQUITTO_PUB_DEV"
		export BINMOSQUITTO_PUB_PHONY_CLEAN="BINMOSQUITTO_PUB_CLEAN"
		export BINMOSQUITTO_PUB_CFLAGS=
		export BINMOSQUITTO_PUB_LDFLAGS=
		echo "BINMOSQUITTO_PUB=${BINMOSQUITTO_PUB}"
	fi

	unset BINMOSQUITTO_SUB_PHONY
	unset BINMOSQUITTO_SUB_PHONY_CLEAN
	if [ "${HAVE_BIN_MOSQUITTO_SUB}" = "1" ]; then
		export BINMOSQUITTO_SUB_NAME="mosquitto_sub"
		export BINMOSQUITTO_SUB="$1"
		export BINMOSQUITTO_SUB_OBJS_DIR=${RUNTIME_OBJS}${BINMOSQUITTO_SUB/${ROOT}/""}
		export BINMOSQUITTO_SUB_BIN="${RUNTIME_BIN}/${BINMOSQUITTO_SUB_NAME}${BINSUFFIX}"
		export BINMOSQUITTO_SUB_BIN_CLEAN="${BINMOSQUITTO_SUB_BIN}_clean"
		export BINMOSQUITTO_SUB_PHONY="BINMOSQUITTO_SUB"
		export BINMOSQUITTO_SUB_PHONY_DEV="BINMOSQUITTO_SUB_DEV"
		export BINMOSQUITTO_SUB_PHONY_CLEAN="BINMOSQUITTO_SUB_CLEAN"
		export BINMOSQUITTO_SUB_CFLAGS=
		export BINMOSQUITTO_SUB_LDFLAGS=
		echo "BINMOSQUITTO_SUB=${BINMOSQUITTO_SUB}"
	fi
fi

