# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset LIBMOSQUITTO_ALL_PHONY
	unset LIBMOSQUITTO_ALL_PHONY_CLEAN
	if [ "${HAVE_LIB_MOSQUITTO_ALL}" = "1" ]; then
		export LIBMOSQUITTO_ALL_NAME="libmosquitto_all"
		export LIBMOSQUITTO_ALL="$1"
		export LIBMOSQUITTO_ALL_OBJS_DIR=${RUNTIME_OBJS}${LIBMOSQUITTO_ALL/${ROOT}/""}
		export LIBMOSQUITTO_ALL_DLL="${RUNTIME_DLL}/${LIBMOSQUITTO_ALL_NAME}.${DLLSUFFIX}"
		export LIBMOSQUITTO_ALL_DLL_CLEAN="${LIBMOSQUITTO_ALL_DLL}_clean"
		export LIBMOSQUITTO_ALL_PHONY="LIBMOSQUITTO_ALL"
		export LIBMOSQUITTO_ALL_PHONY_DEV="LIBMOSQUITTO_ALL_DEV"
		export LIBMOSQUITTO_ALL_PHONY_CLEAN="LIBMOSQUITTO_ALL_CLEAN"
		export LIBMOSQUITTO_ALL_CFLAGS=-DLIBMOSQUITTO_ALL_DLL="\\\"${LIBMOSQUITTO_ALL_NAME}.${DLLSUFFIX}\\\""
		export LIBMOSQUITTO_ALL_LDFLAGS=-lmosquitto${LDLLSUFFIX}
		echo "LIBMOSQUITTO_ALL=${LIBMOSQUITTO_ALL}"
	fi
fi


