# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset LIBMOSQUITTO_PHONY
	unset LIBMOSQUITTO_PHONY_CLEAN
	if [ "${HAVE_LIB_MOSQUITTO}" = "1" ]; then
		export LIBMOSQUITTO_NAME="libmosquitto"
		export LIBMOSQUITTO="$1"
		export LIBMOSQUITTO_OBJS_DIR=${RUNTIME_OBJS}${LIBMOSQUITTO/${ROOT}/""}
		export LIBMOSQUITTO_DLL="${RUNTIME_DLL}/${LIBMOSQUITTO_NAME}.${DLLSUFFIX}"
		export LIBMOSQUITTO_DLL_CLEAN="${LIBMOSQUITTO_DLL}_clean"
		export LIBMOSQUITTO_PHONY="LIBMOSQUITTO"
		export LIBMOSQUITTO_PHONY_DEV="LIBMOSQUITTO_DEV"
		export LIBMOSQUITTO_PHONY_CLEAN="LIBMOSQUITTO_CLEAN"
		export LIBMOSQUITTO_CFLAGS=-DLIBMOSQUITTO_DLL="\\\"${LIBMOSQUITTO_NAME}.${DLLSUFFIX}\\\""
		export LIBMOSQUITTO_LDFLAGS=-lmosquitto${LDLLSUFFIX}
		echo "LIBMOSQUITTO=${LIBMOSQUITTO}"
	fi
fi


