# Copyright (c) 2018, Gary Huang, deepkh@gmail.com, https://github.com/deepkh
#
# Permission to use, copy, modify, and distribute this software for any
# purpose with or without fee is hereby granted, provided that the above
# copyright notice and this permission notice appear in all copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES
# WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF
# MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR
# ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN
# ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF
# OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.
#!/bin/bash

if [ ! -z "$1" ]; then
	unset BINMOSQUITTO_PHONY
	unset BINMOSQUITTO_PHONY_CLEAN
	if [ "${HAVE_BIN_MOSQUITTO}" = "1" ]; then
		export BINMOSQUITTO_NAME="mosquitto"
		export BINMOSQUITTO="$1"
		export BINMOSQUITTO_OBJS_DIR=${RUNTIME_OBJS}${BINMOSQUITTO/${ROOT}/""}
		export BINMOSQUITTO_BIN="${RUNTIME_BIN}/${BINMOSQUITTO_NAME}${BINSUFFIX}"
		export BINMOSQUITTO_BIN_CLEAN="${BINMOSQUITTO_BIN}_clean"
		export BINMOSQUITTO_PHONY="BINMOSQUITTO"
		export BINMOSQUITTO_PHONY_DEV="BINMOSQUITTO_DEV"
		export BINMOSQUITTO_PHONY_CLEAN="BINMOSQUITTO_CLEAN"
		export BINMOSQUITTO_CFLAGS=
		export BINMOSQUITTO_LDFLAGS=
		echo "BINMOSQUITTO=${BINMOSQUITTO}"
	fi

	unset BINMOSQUITTO_PASSWD_PHONY
	unset BINMOSQUITTO_PASSWD_PHONY_CLEAN
	if [ "${HAVE_BIN_MOSQUITTO_PASSWD}" = "1" ]; then
		export BINMOSQUITTO_PASSWD_NAME="mosquitto_passwd"
		export BINMOSQUITTO_PASSWD="$1"
		export BINMOSQUITTO_PASSWD_OBJS_DIR=${RUNTIME_OBJS}${BINMOSQUITTO_PASSWD/${ROOT}/""}
		export BINMOSQUITTO_PASSWD_BIN="${RUNTIME_BIN}/${BINMOSQUITTO_PASSWD_NAME}${BINSUFFIX}"
		export BINMOSQUITTO_PASSWD_BIN_CLEAN="${BINMOSQUITTO_PASSWD_BIN}_clean"
		export BINMOSQUITTO_PASSWD_PHONY="BINMOSQUITTO_PASSWD"
		export BINMOSQUITTO_PASSWD_PHONY_DEV="BINMOSQUITTO_PASSWD_DEV"
		export BINMOSQUITTO_PASSWD_PHONY_CLEAN="BINMOSQUITTO_PASSWD_CLEAN"
		export BINMOSQUITTO_PASSWD_CFLAGS=
		export BINMOSQUITTO_PASSWD_LDFLAGS=
		echo "BINMOSQUITTO_PASSWD=${BINMOSQUITTO_PASSWD}"
	fi
fi

